### PR TITLE
Remove project requirement

### LINKED ISSUE #106: rally.yml "projects" property cannot be omitted (commented out) w/out causing a failure
**Describe the bug**

rally.yml file contains:
```
      # Which projects this repo will link to.
      # To have it connect to any project, leave this value blank
      projects:
      #  - Sample Project

```
If "projects:" is commented out the application will fail with an error (See below) and not process the check.

**To Reproduce**
1. Follow standard installation steps for project 
2. When configuring rally.yml comment out the projects: property (and associated values below it),
3. Start application (I.e. npm start) and monitor output
4. Issue a commit under repository that application is monitoring
5. Watch for error and check failure.

**Expected behavior**
If "projects:" yml configuration is commented out the application should not fail, but still communicate with Rally (ignoring specific project).

```
9:12:20.665Z ERROR event: Cannot read property 'map' of undefined (id=bbbfd500-e186-11ea-99fc-f0362d48b04c)
  TypeError: Cannot read property 'map' of undefined
      at RallyValidate.processArtifacts (/opt/gitrallyapp/lib/RallyValidate.js:255:56)
      at RallyValidate.handlePullRequest (/opt/gitrallyapp/lib/RallyValidate.js:171:53)
  --
  event: {
    "event": "pull_request.edited",
    "id": "bbbfd500-e186-11ea-99fc-f0362d48b04c",
    "installation": 291,
    "repository": "ESD/DA"
  }
19:12:20.665Z ERROR probot: Cannot read property 'map' of undefined
  TypeError: Cannot read property 'map' of undefined
      at RallyValidate.processArtifacts (/opt/gitrallyapp/lib/RallyValidate.js:255:56)
      at RallyValidate.handlePullRequest (/opt/gitrallyapp/lib/RallyValidate.js:171:53)
19:12:20.665Z  INFO http: POST / 500 - 1373.21 ms (id=bbbfd500-e186-11ea-99fc-f0362d48b04c)
19:12:20.665Z TRACE http:  (id=bbbfd500-e186-11ea-99fc-f0362d48b04c, res.duration=1373.21)
  HTTP/1.1 500 Internal Server Error
  x-powered-by: Express
  x-request-id: bbbfd500-e186-11ea-99fc-f0362d48b04c
```

### PR DESCRIPTION
**Pull request by primetheus**
Closes #106 

## Proposed Changes

- Remove requirement for projects to be defined in config

The current config _requires_ the definition of a project
```yaml
rally:
  projects:
    - Project 1
    - Project 2
  workspace: 12345
```

This pull request allows the following settings as well

```yaml
rally:
  projects: 
    - Any
  workspace: 12345
```

```yaml
rally:
  projects: []
  workspace: 12345
```

```yaml
rally:
  workspace: 12345
```

## Readiness Checklist

- [x] If this change requires documentation, it has been included in this pull request

## Reviewer Checklist

- [x] If a functional change has occurred, testing the integration has been performed
- [x] This PR has been categorized with a label (1 of `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`) for the changelog

### CODE REVIEW

File: lib/RallyValidate.js [hunk 1]
```diff
@@ -55,6 +55,9 @@ class RallyValidate {
       if (config.rally.api_key) { // Rally API key, to override global default
         rallyAPIKey = config.rally.api_key
       }
+      if (!config.rally.projects || config.rally.projects.length < 1) {
```
Comment (admiralAwkbar) [inline lib/RallyValidate.js:58]: much improvment.. such wow
